name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Build the Docker Image
<<<<<<< HEAD
        run: docker build  -t jagyasenbhatra/fastapi:v1 .
=======
        run: docker build  -t fastapi:v1 .
>>>>>>> 4b24642730b5f167f7c6c6c2ec83e3d774ce3eb4

  test:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test  
    steps:
        - uses: actions/checkout@v3
        # - name: Pull Docker image
        #   run : docker pull jagyasenbhatra/fastapi:v1
        # - name: Run Docker image
        #   run : docker run -it -p 8000:8000 jagyasenbhatra/fastapi:v1
