name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'

      - name: Install Dependencies
        run: pip install -r requirements.txt

  test:
      runs-on: ubuntu-latest
      steps:
         - name: Run Tests
           run: pytest
  
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker Image
        run: docker build -t jagyasenbhatra/fastapi:v15 .

  push:
    runs-on: ubuntu-latest
    steps:
     - name: Log in to Docker Registry
       uses: docker/login-action@v2
       with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
     - name: Push the Docker Image
       run: docker push  jagyasenbhatra/fastapi:v15


