name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Build the Docker Image
        run: docker build -t jagyasenbhatra/my-fastapi-app:latest .

  test:
    runs-on: ubuntu-latest
    needs: build  # Only run after build finishes successfully
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Only run after tests pass
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jagyasenbhatra
          password: ${{ secrets.dckr_pat_TVD1yj7WmuNq935hp-foW7ra_hA }}
      - name: Push the Docker Image
        run: docker push jagyasenbhatra/my-fastapi-app:latest